apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node-1
  name: node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/noria-default: "true"
        io.kompose.service: node-1
    spec:
      containers:
        - env:
            - name: CHAIN_ID
              value: '"oasis-3"'
            - name: DENOM
              value: '"unoria"'
            - name: GAS_PRICE
              value: '"0.0025"'
            - name: GAS_PRICE_DENOM
              value: '"ucrd"'
            - name: GENESIS_URL
              value: https://raw.githubusercontent.com/noria-net/noria/main/genesis.json
            - name: MINIMUM_GAS_PRICES
              value: 0.00125ucrd
            - name: MONIKER
              value: node_1
            - name: NORIAD_CONSENSUS_TIMEOUT_COMMIT
              value: 1500ms
            - name: P2P_PERSISTENT_PEERS
              value: c166422d24413f0661b006af29f7545890a9a1f0@54.173.208.94:26656
          image: docker pull docker pull ghcr.io/nextnet-works/noria:v1.0.0
          name: node-1
          ports:
            - containerPort: 26656
            - containerPort: 26657
            - containerPort: 1317
          resources: {}
          volumeMounts:
            - mountPath: /root/.noria
              name: node-1-claim0
      restartPolicy: Always
      volumes:
        - name: node-1-claim0
          persistentVolumeClaim:
            claimName: node-1-claim0
status: {}
