version: '3.4'
services:
  node_1:
    image: ghcr.io/ovrclk/cosmos-omnibus:v0.2.3-generic
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/NextNet-Works/net/master/noria/meta.json
    # - BINARY_ZIP_PATH=akash_0.15.0-rc14_linux_amd64/akash
      - BINARY_URL=https://github.com/noria-net/noria/archive/refs/tags/v1.0.0.zip
      - PROJECT=noria
      - PROJECT_BIN=noriad
      - PROJECT_DIR=.$PROJECT_BIN
    volumes:
      - ./node-data:/root/.noria
